[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake", "pkg-config", "systemd", "nodejs_20"]

[phases.install]
cmds = ["npm install -g node-gyp && bun install"]

[phases.build]
cmds = ["bunx next build --no-turbo"]

[start]
cmd = "bun run start"
