[phases.setup]
nixPkgs = ["python3", "gcc", "gnumake", "pkg-config", "systemd", "nodejs_20"]

[phases.install]
cmds = ["npm install -g node-gyp && bun install"]

[phases.build]
cmds = ["TURBOPACK=0 bun run build"]

[start]
cmd = "bun run start"
